blank_issues_enabled: true
contact_links:
    - name: Will You Snail Modding Discord
      url: https://discord.gg/Wtm5y8aNGH
      about: Please ask and answer questions regarding this program (or modding as a whole) here.
